### ISSUE TITLE
[Enhancement] Using Nacos NamingService to save meta data.

### ISSUE THREAD

**Issue by karsonto** [apache/eventmesh#4843]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

When using Nacos as a meta service should use naming service to save meta data.

### Describe the solution you'd like

When using nacos as meta storage, it uses configservice to save client info curenly.
<img width="1204" alt="image" src="https://github.com/apache/eventmesh/assets/31433550/76906404-7eb4-4c9c-9b17-93b41996d916">
<img width="1196" alt="image" src="https://github.com/apache/eventmesh/assets/31433550/1b8517ba-b5c6-466b-aeda-bf2cb6c57fee">

But I think this usage is inappropriate, because when nacos uses a cluster, config data will be persisted to the database, TPS is very low, and these service-related information should be saved to the metadata of the registration center
<img width="1286" alt="image" src="https://github.com/apache/eventmesh/assets/31433550/7c7294a6-2244-4986-88fb-7a223652ea9c">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by xwm1992** [comment]
As far as I know, nacos name service has no way to persist the meta data to be stored, why do you want to use name service instead of config service?

**Comment by xwm1992** [comment]
> I have found that subscriber information is stored on meta storage, which is frequently updated and not suitable for persistent storage.

But if you use name service, if one eventmesh goes down, how can you ensure that the subscription information on this eventmesh is loaded to other meshes?

**Comment by karsonto** [comment]
You can consider using a permanent instance to save the mata data when registering, and the information should not be lost when the server goes down.
