### ISSUE TITLE
[Feature] Support Jraft algorithm as meta storage

### ISSUE THREAD

**Issue by karsonto** [apache/eventmesh#4852]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

I think the implementation of this feature could streamline the em cluster architecture and allow em clusters to have meta data communication capabilities

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by karsonto** [comment]
I will try to do it.
